apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather
spec:
  schedule: "*/5 * * * * "
  jobTemplate:      
    spec:                  
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/tech-aw/weather
            imagePullPolicy: Always
            name: weather
            env:
              - name: INFLUXDB_SERVICE_HOST_PORT
                value: "http://$(INFLUXDB_SERVICE_HOST):$(INFLUXDB_SERVICE_PORT)"
            envFrom:
              - secretRef:
                  name: tibber-secret
              - configMapRef:
                  name: tibber-config
          restartPolicy: OnFailure
